# Generated by Django 5.1.3 on 2024-12-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
